version: "3"

services:
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    env_file:
      - ./api/.env
    environment:
      - PS_HOST=db
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./api/.env
    environment:
      POSTGRES_USER: $PS_USERNAME
      POSTGRES_PASSWORD: $PS_PASSWORD
    ports:
      - "5432:5432"
    

